import { DatabaseSchema } from '../types/index.ts';

export const initialDatabase: DatabaseSchema = {
  settings: {
    userName: 'Geovane Silva',
    companyName: 'GS Digital Studio',
    logoUrl: '',
    email: 'geovane.silvaa2010@gmail.com',
    whatsapp: '',
    contactDetails: '',
    currency: 'R$',
    hourlyRateGoal: 100,
    monthlyRevenueGoal: 5000,
    pixKey: '',
    theme: 'light',
  },
  services: [],
  servicePackages: [],
  clients: [],
  leads: [],
  projects: [],
  portfolio: [],
  payments: [],
  installments: [],
  expenses: [],
  timeLogs: [],
  tasks: [],
  proposals: [],
  events: [],
  clientHistory: [],
  files: [],
  personalNotes: [
    {
      id: 'note-welcome-1',
      title: 'Minhas Observações & Mensagens',
      content: 'Aqui você pode guardar anotações para si mesmo: insights de reuniões, ideias de serviços, links rápidos, metas da semana ou qualquer rascunho pessoal.\n\nUse o botão de fixar para manter mensagens importantes no topo!',
      category: 'general',
      color: 'indigo',
      pinned: true,
      createdAt: '2026-09-25T12:00:00Z',
      updatedAt: '2026-09-25T12:00:00Z',
    },
  ],
  scratchpad: '',
};

export const demoDatabase: DatabaseSchema = {
  settings: {
    userName: 'Geovane Silva',
    companyName: 'GS Digital Studio',
    logoUrl: '',
    email: 'geovane.silvaa2010@gmail.com',
    whatsapp: '11998765432',
    contactDetails: 'São Paulo, SP - Criação de Landing Pages de Alta Conversão e Sites Modernos',
    currency: 'R$',
    hourlyRateGoal: 120,
    theme: 'light',
  },
  personalNotes: [
    {
      id: 'note-demo-1',
      title: 'Checklist para Fechamento de Contratos',
      content: '1. Confirmar CNPJ/CPF e razão social\n2. Enviar proposta formal em PDF ou link\n3. Solicitar sinal de 50% via PIX antes de iniciar o design no Figma\n4. Agendar reunião de alinhamento de briefing de 30 min',
      category: 'reminder',
      color: 'emerald',
      pinned: true,
      createdAt: '2026-09-20T14:30:00Z',
      updatedAt: '2026-09-20T14:30:00Z',
    },
    {
      id: 'note-demo-2',
      title: 'Ideias de novos pacotes de serviços',
      content: '- Pacote de Manutenção Mensal & Hospedagem R$ 250/mês\n- Otimização de Performance e Core Web Vitals R$ 800\n- Consultoria de CRO (Otimização de Taxa de Conversão)',
      category: 'idea',
      color: 'amber',
      pinned: false,
      createdAt: '2026-09-22T09:15:00Z',
      updatedAt: '2026-09-22T09:15:00Z',
    },
  ],
  scratchpad: 'Lembrete: entrar em contato com os clientes da semana passada na sexta-feira à tarde.',

  services: [
    {
      id: 'srv-1',
      name: 'Landing Page de Alta Conversão',
      description: 'Página única focada em conversão, com copywriting estratégico, design responsivo e integração com WhatsApp e CRM.',
      defaultPrice: 1500,
      estimatedCost: 150,
      averageDeliveryDays: 7,
      createdAt: '2026-01-10T10:00:00Z',
    },
    {
      id: 'srv-2',
      name: 'Site Institucional Completo',
      description: 'Site multipáginas (Início, Sobre, Serviços, Portfólio, Contato) com painel gerenciável e otimização SEO.',
      defaultPrice: 3200,
      estimatedCost: 300,
      averageDeliveryDays: 18,
      createdAt: '2026-01-10T10:00:00Z',
    },
    {
      id: 'srv-3',
      name: 'E-commerce / Loja Virtual',
      description: 'Loja com catálogo de produtos, cálculo de frete Correios/Melhor Envio e checkout integrado.',
      defaultPrice: 4500,
      estimatedCost: 500,
      averageDeliveryDays: 25,
      createdAt: '2026-01-10T10:00:00Z',
    },
    {
      id: 'srv-4',
      name: 'Manutenção e Hospedagem Mensal',
      description: 'Hospedagem rápida em nuvem, backups diários, segurança SSL e até 2 horas de alterações por mês.',
      defaultPrice: 250,
      estimatedCost: 35,
      averageDeliveryDays: 30,
      createdAt: '2026-01-10T10:00:00Z',
    },
    {
      id: 'srv-5',
      name: 'Redesign e Otimização de Performance',
      description: 'Modernização visual de sites antigos com melhoria de pontuação no Google PageSpeed Insights.',
      defaultPrice: 1800,
      estimatedCost: 120,
      averageDeliveryDays: 10,
      createdAt: '2026-01-10T10:00:00Z',
    },
  ],

  clients: [
    {
      id: 'cli-1',
      companyName: 'Barbearia Vintage Club',
      contactName: 'Carlos Eduardo',
      phone: '(11) 98765-4321',
      whatsapp: '11987654321',
      instagram: '@barbeariavintageclub',
      email: 'contato@barbeariavintage.com.br',
      city: 'São Paulo - SP',
      niche: 'Beleza & Cuidados',
      firstContactDate: '2026-02-05',
      origin: 'Instagram',
      notes: 'Cliente busca modernizar captação de agendamentos no WhatsApp via landing page rápida.',
      status: 'active_client',
      createdAt: '2026-02-05T14:30:00Z',
      updatedAt: '2026-03-01T10:00:00Z',
    },
    {
      id: 'cli-2',
      companyName: 'Clínica OdontoSorriso',
      contactName: 'Dra. Mariana Freitas',
      phone: '(11) 97654-3210',
      whatsapp: '11976543210',
      instagram: '@odontosorriso.sp',
      email: 'mariana@odontosorriso.com.br',
      city: 'Campinas - SP',
      niche: 'Saúde & Odontologia',
      firstContactDate: '2026-02-15',
      origin: 'Indicação',
      notes: 'Site institucional completo com formulário para marcação de consultas e detalhes dos tratamentos.',
      status: 'project_in_progress',
      createdAt: '2026-02-15T09:00:00Z',
      updatedAt: '2026-03-10T16:00:00Z',
    },
    {
      id: 'cli-3',
      companyName: 'Academia IronFit',
      contactName: 'Rodrigo Lima',
      phone: '(19) 99123-4567',
      whatsapp: '19991234567',
      instagram: '@ironfitacademia',
      email: 'rodrigo@ironfit.com.br',
      city: 'Ribeirão Preto - SP',
      niche: 'Fitness & Treino',
      firstContactDate: '2026-03-01',
      origin: 'Prospecção Ativa',
      notes: 'Landing page para venda de plano trimestral com contador regressivo.',
      status: 'awaiting_response',
      createdAt: '2026-03-01T11:20:00Z',
      updatedAt: '2026-03-15T14:00:00Z',
    },
    {
      id: 'cli-4',
      companyName: 'Advocacia Silva & Associados',
      contactName: 'Dra. Patrícia Silva',
      phone: '(11) 98877-6655',
      whatsapp: '11988776655',
      instagram: '@silvaadvogados',
      email: 'patricia@silvaadv.com.br',
      city: 'Santos - SP',
      niche: 'Direito Previdenciário e Trabalhista',
      firstContactDate: '2026-01-20',
      origin: 'Google Meu Negócio',
      notes: 'Site corporativo concluído com sucesso e elogios do cliente.',
      status: 'project_completed',
      createdAt: '2026-01-20T10:00:00Z',
      updatedAt: '2026-02-28T18:00:00Z',
    },
    {
      id: 'cli-5',
      companyName: 'Cafeteria Grão Raro',
      contactName: 'Henrique Prado',
      phone: '(11) 97111-2233',
      whatsapp: '11971112233',
      instagram: '@graorarocafe',
      email: 'henrique@graoraro.com.br',
      city: 'São Paulo - SP',
      niche: 'Gastronomia',
      firstContactDate: '2026-03-05',
      origin: 'Instagram',
      notes: 'Interessado em cardápio digital e página de eventos com reserva.',
      status: 'negotiating',
      createdAt: '2026-03-05T15:00:00Z',
      updatedAt: '2026-03-18T10:00:00Z',
    },
    {
      id: 'cli-6',
      companyName: 'Pizzaria Bella Itália',
      contactName: 'Giuseppe Rossi',
      phone: '(11) 96543-2198',
      whatsapp: '11965432198',
      instagram: '@bellaitaliapizza',
      email: 'giuseppe@bellaitalia.com',
      city: 'Santo André - SP',
      niche: 'Alimentação',
      firstContactDate: '2026-02-10',
      origin: 'Prospecção Ativa',
      notes: 'Achou o orçamento acima do esperado no momento.',
      status: 'lost_client',
      createdAt: '2026-02-10T13:00:00Z',
      updatedAt: '2026-02-18T11:00:00Z',
    },
  ],

  leads: [
    {
      id: 'lead-1',
      clientId: 'cli-3',
      name: 'Rodrigo Lima',
      company: 'Academia IronFit',
      niche: 'Fitness & Treino',
      whatsapp: '19991234567',
      instagram: '@ironfitacademia',
      currentWebsite: 'https://ironfit-teste.wixsite.com',
      city: 'Ribeirão Preto - SP',
      contactDate: '2026-03-01',
      lastContactDate: '2026-03-15',
      nextContactDate: '2026-03-22',
      proposalValue: 1800,
      stage: 'awaiting_response',
      notes: 'Apresentada proposta de Landing Page focada em matrículas.',
      followUpReminder: 'Cobrar resposta sobre a proposta enviada na semana passada.',
      createdAt: '2026-03-01T11:20:00Z',
    },
    {
      id: 'lead-2',
      clientId: 'cli-5',
      name: 'Henrique Prado',
      company: 'Cafeteria Grão Raro',
      niche: 'Gastronomia',
      whatsapp: '11971112233',
      instagram: '@graorarocafe',
      currentWebsite: '',
      city: 'São Paulo - SP',
      contactDate: '2026-03-05',
      lastContactDate: '2026-03-18',
      nextContactDate: '2026-03-23',
      proposalValue: 2400,
      stage: 'negotiating',
      notes: 'Ajustando detalhes sobre integração com reservas de mesas.',
      followUpReminder: 'Enviar simulação de parcelamento em 3x sem juros.',
      createdAt: '2026-03-05T15:00:00Z',
    },
    {
      id: 'lead-3',
      name: 'Larissa Becker',
      company: 'Studio Pilates Viver Bem',
      niche: 'Saúde & Bem-estar',
      whatsapp: '11993334444',
      instagram: '@viverbempilates',
      currentWebsite: '',
      city: 'São Bernardo - SP',
      contactDate: '2026-03-12',
      lastContactDate: '2026-03-19',
      nextContactDate: '2026-03-24',
      proposalValue: 1600,
      stage: 'proposal_sent',
      notes: 'Briefing inicial realizado por chamada de vídeo. Proposta enviada em PDF.',
      followUpReminder: 'Verificar se Larissa conseguiu abrir e analisar os protótipos.',
      createdAt: '2026-03-12T16:40:00Z',
    },
    {
      id: 'lead-4',
      name: 'Dr. Fernando Dias',
      company: 'Dias Arquitetura Sustentável',
      niche: 'Arquitetura & Urbanismo',
      whatsapp: '11982221100',
      instagram: '@diasarquitetura',
      currentWebsite: 'https://diasarq.com.br',
      city: 'São Paulo - SP',
      contactDate: '2026-03-18',
      lastContactDate: '2026-03-18',
      nextContactDate: '2026-03-21',
      proposalValue: 3500,
      stage: 'first_contact',
      notes: 'Encontrado no Instagram com fotos excelentes mas site lento e desconfigurado no mobile.',
      followUpReminder: 'Enviar mensagem no WhatsApp apresentando melhorias para o portfólio dele.',
      createdAt: '2026-03-18T14:15:00Z',
    },
    {
      id: 'lead-5',
      name: 'Marcos Vinicius',
      company: 'Mecânica Express Auto',
      niche: 'Automotivo',
      whatsapp: '11985554433',
      instagram: '@expressautomotivo',
      currentWebsite: '',
      city: 'Guarulhos - SP',
      contactDate: '2026-03-19',
      lastContactDate: '2026-03-19',
      nextContactDate: '2026-03-25',
      proposalValue: 1400,
      stage: 'leads_found',
      notes: 'Lead encontrado no Google Maps com boa avaliação e sem site.',
      followUpReminder: 'Fazer o primeiro contato pelo WhatsApp na quarta-feira.',
      createdAt: '2026-03-19T09:30:00Z',
    },
    {
      id: 'lead-6',
      clientId: 'cli-1',
      name: 'Carlos Eduardo',
      company: 'Barbearia Vintage Club',
      niche: 'Beleza & Cuidados',
      whatsapp: '11987654321',
      instagram: '@barbeariavintageclub',
      currentWebsite: 'https://barbeariavintage.com.br',
      city: 'São Paulo - SP',
      contactDate: '2026-02-05',
      lastContactDate: '2026-02-08',
      nextContactDate: '',
      proposalValue: 1500,
      stage: 'closed',
      notes: 'Projeto fechado com 50% de entrada!',
      followUpReminder: 'Oferecer contrato de manutenção preventiva após 30 dias.',
      createdAt: '2026-02-05T14:30:00Z',
    },
    {
      id: 'lead-7',
      clientId: 'cli-6',
      name: 'Giuseppe Rossi',
      company: 'Pizzaria Bella Itália',
      niche: 'Alimentação',
      whatsapp: '11965432198',
      instagram: '@bellaitaliapizza',
      currentWebsite: '',
      city: 'Santo André - SP',
      contactDate: '2026-02-10',
      lastContactDate: '2026-02-18',
      nextContactDate: '',
      proposalValue: 1600,
      stage: 'lost',
      notes: 'Decidiu postergar investimento para o segundo semestre.',
      followUpReminder: '',
      createdAt: '2026-02-10T13:00:00Z',
    },
  ],

  projects: [
    {
      id: 'prj-1',
      name: 'Landing Page Barbearia Vintage',
      clientId: 'cli-1',
      serviceType: 'Landing Page de Alta Conversão',
      startDate: '2026-02-10',
      deliveryDeadline: '2026-02-25',
      completionDate: '2026-02-24',
      chargedPrice: 1500,
      projectCost: 150,
      estimatedHours: 12,
      actualHours: 10.5,
      progress: 100,
      status: 'completed',
      notes: 'Landing page entregue antes do prazo. Cliente muito satisfeito!',
      createdAt: '2026-02-10T10:00:00Z',
      updatedAt: '2026-02-24T18:00:00Z',
    },
    {
      id: 'prj-2',
      name: 'Site Institucional OdontoSorriso',
      clientId: 'cli-2',
      serviceType: 'Site Institucional Completo',
      startDate: '2026-03-01',
      deliveryDeadline: '2026-03-28',
      completionDate: '',
      chargedPrice: 3200,
      projectCost: 280,
      estimatedHours: 24,
      actualHours: 18,
      progress: 75,
      status: 'in_progress',
      notes: 'Página inicial e páginas internas criadas. Aguardando textos finais da doutora.',
      createdAt: '2026-03-01T09:00:00Z',
      updatedAt: '2026-03-18T15:30:00Z',
    },
    {
      id: 'prj-3',
      name: 'Portal Jurídico Silva & Associados',
      clientId: 'cli-4',
      serviceType: 'Site Institucional Completo',
      startDate: '2026-01-25',
      deliveryDeadline: '2026-02-20',
      completionDate: '2026-02-18',
      chargedPrice: 3400,
      projectCost: 250,
      estimatedHours: 22,
      actualHours: 20,
      progress: 100,
      status: 'completed',
      notes: 'Site publicado no domínio oficial com certificado SSL configurado.',
      createdAt: '2026-01-25T11:00:00Z',
      updatedAt: '2026-02-18T17:00:00Z',
    },
  ],

  portfolio: [
    {
      id: 'port-1',
      projectId: 'prj-1',
      clientId: 'cli-1',
      clientName: 'Barbearia Vintage Club',
      siteName: 'Landing Page Vintage Club',
      publishedUrl: 'https://barbeariavintageclub.exemplo.com',
      githubUrl: 'https://github.com/geovanesilva/barbearia-vintage-lp',
      domainUrl: 'barbeariavintage.com.br',
      platform: 'React + Tailwind + Vite',
      deliveryDate: '2026-02-24',
      receivedAmount: 1500,
      coverImage: 'https://images.unsplash.com/photo-1503951914875-452162b0f3f1?w=800&auto=format&fit=crop&q=80',
      description: 'Landing page rápida, moderna e focada em agendamentos pelo WhatsApp com visual retrô premium.',
      technologies: ['React', 'Tailwind CSS', 'Framer Motion', 'TypeScript'],
      isPublic: true,
      createdAt: '2026-02-24T19:00:00Z',
    },
    {
      id: 'port-2',
      projectId: 'prj-3',
      clientId: 'cli-4',
      clientName: 'Advocacia Silva & Associados',
      siteName: 'Portal Advocacia Silva',
      publishedUrl: 'https://silvaadvogados.exemplo.com',
      githubUrl: 'https://github.com/geovanesilva/silva-advocacia-site',
      domainUrl: 'silvaadv.com.br',
      platform: 'Next.js + Tailwind',
      deliveryDate: '2026-02-18',
      receivedAmount: 3400,
      coverImage: 'https://images.unsplash.com/photo-1486406146926-c627a92ad1ab?w=800&auto=format&fit=crop&q=80',
      description: 'Site corporativo de alta sobriedade e sofisticação com áreas de atuação jurídica e blog informativo.',
      technologies: ['Next.js', 'Tailwind CSS', 'SEO Otimizado', 'Node.js'],
      isPublic: true,
      createdAt: '2026-02-18T18:00:00Z',
    },
  ],

  payments: [
    {
      id: 'pay-1',
      projectId: 'prj-1',
      clientId: 'cli-1',
      title: 'Landing Page Barbearia Vintage',
      totalAmount: 1500,
      receivedAmount: 1500,
      pendingAmount: 0,
      costs: 150,
      profit: 1350,
      status: 'paid',
      installments: [],
      createdAt: '2026-02-10T10:00:00Z',
    },
    {
      id: 'pay-2',
      projectId: 'prj-2',
      clientId: 'cli-2',
      title: 'Site Institucional OdontoSorriso',
      totalAmount: 3200,
      receivedAmount: 1600,
      pendingAmount: 1600,
      costs: 280,
      profit: 1320,
      status: 'partial',
      installments: [],
      createdAt: '2026-03-01T09:00:00Z',
    },
    {
      id: 'pay-3',
      projectId: 'prj-3',
      clientId: 'cli-4',
      title: 'Portal Jurídico Silva & Associados',
      totalAmount: 3400,
      receivedAmount: 3400,
      pendingAmount: 0,
      costs: 250,
      profit: 3150,
      status: 'paid',
      installments: [],
      createdAt: '2026-01-25T11:00:00Z',
    },
  ],

  installments: [
    {
      id: 'inst-1',
      paymentId: 'pay-1',
      projectId: 'prj-1',
      clientId: 'cli-1',
      installmentNumber: 1,
      totalInstallments: 2,
      amount: 750,
      dueDate: '2026-02-10',
      paidDate: '2026-02-10',
      status: 'paid',
      paymentMethod: 'pix',
      notes: 'Entrada de 50% via Pix',
    },
    {
      id: 'inst-2',
      paymentId: 'pay-1',
      projectId: 'prj-1',
      clientId: 'cli-1',
      installmentNumber: 2,
      totalInstallments: 2,
      amount: 750,
      dueDate: '2026-02-24',
      paidDate: '2026-02-24',
      status: 'paid',
      paymentMethod: 'pix',
      notes: 'Quitação na entrega do projeto',
    },
    {
      id: 'inst-3',
      paymentId: 'pay-2',
      projectId: 'prj-2',
      clientId: 'cli-2',
      installmentNumber: 1,
      totalInstallments: 2,
      amount: 1600,
      dueDate: '2026-03-01',
      paidDate: '2026-03-01',
      status: 'paid',
      paymentMethod: 'pix',
      notes: 'Entrada de 50% via Pix',
    },
    {
      id: 'inst-4',
      paymentId: 'pay-2',
      projectId: 'prj-2',
      clientId: 'cli-2',
      installmentNumber: 2,
      totalInstallments: 2,
      amount: 1600,
      dueDate: '2026-03-28',
      paidDate: undefined,
      status: 'pending',
      paymentMethod: 'pix',
      notes: 'Saldo final previsto para a entrega oficial',
    },
    {
      id: 'inst-5',
      paymentId: 'pay-3',
      projectId: 'prj-3',
      clientId: 'cli-4',
      installmentNumber: 1,
      totalInstallments: 1,
      amount: 3400,
      dueDate: '2026-01-25',
      paidDate: '2026-01-25',
      status: 'paid',
      paymentMethod: 'bank_transfer',
      notes: 'Pagamento integral à vista com desconto',
    },
  ],

  timeLogs: [
    {
      id: 'tl-1',
      clientId: 'cli-1',
      projectId: 'prj-1',
      activity: 'Briefing e Criação da Estrutura (Wireframe)',
      date: '2026-02-11',
      durationMinutes: 150, // 2h30m
      createdAt: '2026-02-11T16:00:00Z',
    },
    {
      id: 'tl-2',
      clientId: 'cli-1',
      projectId: 'prj-1',
      activity: 'Desenvolvimento Front-end e Animações Tailwind',
      date: '2026-02-14',
      durationMinutes: 300, // 5h00m
      createdAt: '2026-02-14T18:00:00Z',
    },
    {
      id: 'tl-3',
      clientId: 'cli-1',
      projectId: 'prj-1',
      activity: 'Integração com WhatsApp e Publicação Vercel',
      date: '2026-02-23',
      durationMinutes: 180, // 3h00m
      createdAt: '2026-02-23T17:00:00Z',
    },
    {
      id: 'tl-4',
      clientId: 'cli-2',
      projectId: 'prj-2',
      activity: 'Arquitetura de Informação e UI Design Figma',
      date: '2026-03-02',
      durationMinutes: 360, // 6h00m
      createdAt: '2026-03-02T19:00:00Z',
    },
    {
      id: 'tl-5',
      clientId: 'cli-2',
      projectId: 'prj-2',
      activity: 'Desenvolvimento das páginas Início e Tratamentos',
      date: '2026-03-08',
      durationMinutes: 480, // 8h00m
      createdAt: '2026-03-08T18:00:00Z',
    },
    {
      id: 'tl-6',
      clientId: 'cli-2',
      projectId: 'prj-2',
      activity: 'Formulário de Agendamento e Responsividade Mobile',
      date: '2026-03-15',
      durationMinutes: 240, // 4h00m
      createdAt: '2026-03-15T16:00:00Z',
    },
    {
      id: 'tl-7',
      clientId: 'cli-4',
      projectId: 'prj-3',
      activity: 'Construção do Portal Jurídico e Otimização SEO',
      date: '2026-02-05',
      durationMinutes: 1200, // 20h00m
      createdAt: '2026-02-05T20:00:00Z',
    },
  ],

  tasks: [
    {
      id: 'tsk-1',
      projectId: 'prj-1',
      clientId: 'cli-1',
      title: 'Criar wireframe e paleta de cores',
      completed: true,
      dueDate: '2026-02-12',
      priority: 'high',
      createdAt: '2026-02-10T10:00:00Z',
    },
    {
      id: 'tsk-2',
      projectId: 'prj-1',
      clientId: 'cli-1',
      title: 'Desenvolver hero section com CTA chamativo',
      completed: true,
      dueDate: '2026-02-15',
      priority: 'high',
      createdAt: '2026-02-10T10:00:00Z',
    },
    {
      id: 'tsk-3',
      projectId: 'prj-1',
      clientId: 'cli-1',
      title: 'Configurar botão flutuante de agendamento WhatsApp',
      completed: true,
      dueDate: '2026-02-18',
      priority: 'medium',
      createdAt: '2026-02-10T10:00:00Z',
    },
    {
      id: 'tsk-4',
      projectId: 'prj-1',
      clientId: 'cli-1',
      title: 'Publicar e apontar DNS para o domínio oficial',
      completed: true,
      dueDate: '2026-02-24',
      priority: 'high',
      createdAt: '2026-02-10T10:00:00Z',
    },
    {
      id: 'tsk-5',
      projectId: 'prj-2',
      clientId: 'cli-2',
      title: 'Criar estrutura e layout inicial das páginas',
      completed: true,
      dueDate: '2026-03-05',
      priority: 'high',
      createdAt: '2026-03-01T09:00:00Z',
    },
    {
      id: 'tsk-6',
      projectId: 'prj-2',
      clientId: 'cli-2',
      title: 'Desenvolver página de especialidades e tratamentos',
      completed: true,
      dueDate: '2026-03-12',
      priority: 'high',
      createdAt: '2026-03-01T09:00:00Z',
    },
    {
      id: 'tsk-7',
      projectId: 'prj-2',
      clientId: 'cli-2',
      title: 'Criar formulário de consulta com validação',
      completed: true,
      dueDate: '2026-03-18',
      priority: 'medium',
      createdAt: '2026-03-01T09:00:00Z',
    },
    {
      id: 'tsk-8',
      projectId: 'prj-2',
      clientId: 'cli-2',
      title: 'Inserir fotos finais da equipe e depoimentos dos pacientes',
      completed: false,
      dueDate: '2026-03-24',
      priority: 'medium',
      createdAt: '2026-03-01T09:00:00Z',
    },
    {
      id: 'tsk-9',
      projectId: 'prj-2',
      clientId: 'cli-2',
      title: 'Revisão final com a cliente e entrega oficial',
      completed: false,
      dueDate: '2026-03-28',
      priority: 'high',
      createdAt: '2026-03-01T09:00:00Z',
    },
  ],

  proposals: [
    {
      id: 'prop-1',
      clientId: 'cli-3',
      serviceId: 'srv-1',
      serviceName: 'Landing Page de Alta Conversão',
      title: 'Landing Page de Matrículas - IronFit',
      description: 'Criação de landing page com foco em captação de novos alunos para o plano trimestral, com contador regressivo e prova social.',
      value: 1800,
      estimatedDays: 8,
      sentDate: '2026-03-15',
      deadlineDate: '2026-03-25',
      status: 'sent',
      createdAt: '2026-03-15T11:00:00Z',
    },
    {
      id: 'prop-2',
      clientId: 'cli-5',
      serviceId: 'srv-2',
      serviceName: 'Site Institucional Completo',
      title: 'Cardápio Digital & Site Cafeteria Grão Raro',
      description: 'Site interativo com cardápio online visual, história da cafeteria e formulário para reserva de eventos corporativos.',
      value: 2400,
      estimatedDays: 14,
      sentDate: '2026-03-17',
      deadlineDate: '2026-03-27',
      status: 'viewed',
      createdAt: '2026-03-17T14:30:00Z',
    },
    {
      id: 'prop-3',
      clientId: 'cli-1',
      serviceId: 'srv-1',
      serviceName: 'Landing Page de Alta Conversão',
      title: 'Landing Page Barbearia Vintage',
      description: 'Desenvolvimento de página web ultra-rápida para agendamento de clientes.',
      value: 1500,
      estimatedDays: 7,
      sentDate: '2026-02-06',
      deadlineDate: '2026-02-15',
      status: 'accepted',
      convertedToProjectId: 'prj-1',
      createdAt: '2026-02-06T09:00:00Z',
    },
  ],

  events: [
    {
      id: 'ev-1',
      title: 'Entrega Prevista - Site OdontoSorriso',
      date: '2026-03-28',
      time: '17:00',
      type: 'delivery',
      relatedId: 'prj-2',
      description: 'Apresentação final das páginas publicadas em ambiente de testes.',
    },
    {
      id: 'ev-2',
      title: 'Vencimento 2ª Parcela OdontoSorriso (R$ 1.600)',
      date: '2026-03-28',
      time: '12:00',
      type: 'payment_due',
      relatedId: 'inst-4',
      description: 'Recebimento do saldo final do projeto.',
    },
    {
      id: 'ev-3',
      title: 'Follow-up Proposta Academia IronFit',
      date: '2026-03-22',
      time: '14:30',
      type: 'follow_up',
      relatedId: 'lead-1',
      description: 'Mensagem no WhatsApp para tirar dúvidas sobre o fechamento.',
    },
    {
      id: 'ev-4',
      title: 'Reunião de Alinhamento Cafeteria Grão Raro',
      date: '2026-03-23',
      time: '10:00',
      type: 'meeting',
      relatedId: 'lead-2',
      description: 'Chamada pelo Google Meet para validar cardápio digital.',
    },
  ],

  clientHistory: [
    {
      id: 'ch-1',
      clientId: 'cli-1',
      date: '2026-02-05',
      type: 'auto_event',
      category: 'created',
      content: 'Cliente cadastrado no sistema via prospecção no Instagram.',
      createdAt: '2026-02-05T14:30:00Z',
    },
    {
      id: 'ch-2',
      clientId: 'cli-1',
      date: '2026-02-06',
      type: 'auto_event',
      category: 'proposal_sent',
      content: 'Proposta comercial enviada no valor de R$ 1.500,00.',
      createdAt: '2026-02-06T09:00:00Z',
    },
    {
      id: 'ch-3',
      clientId: 'cli-1',
      date: '2026-02-08',
      type: 'auto_event',
      category: 'status_change',
      content: 'Proposta aceita pelo cliente. Status alterado para "Confirmado".',
      createdAt: '2026-02-08T11:00:00Z',
    },
    {
      id: 'ch-4',
      clientId: 'cli-1',
      date: '2026-02-10',
      type: 'auto_event',
      category: 'payment_received',
      content: 'Entrada de R$ 750,00 recebida via Pix. Projeto iniciado!',
      createdAt: '2026-02-10T10:00:00Z',
    },
    {
      id: 'ch-5',
      clientId: 'cli-1',
      date: '2026-02-24',
      type: 'auto_event',
      category: 'project_completed',
      content: 'Projeto concluído e publicado. Saldo final de R$ 750,00 quitado.',
      createdAt: '2026-02-24T18:00:00Z',
    },
    {
      id: 'ch-6',
      clientId: 'cli-2',
      date: '2026-02-15',
      type: 'auto_event',
      category: 'created',
      content: 'Cliente indicado pelo Dr. Roberto.',
      createdAt: '2026-02-15T09:00:00Z',
    },
    {
      id: 'ch-7',
      clientId: 'cli-2',
      date: '2026-03-01',
      type: 'auto_event',
      category: 'project_started',
      content: 'Entrada de R$ 1.600 paga via Pix. Projeto do site multipáginas iniciado.',
      createdAt: '2026-03-01T09:00:00Z',
    },
    {
      id: 'ch-8',
      clientId: 'cli-2',
      date: '2026-03-16',
      type: 'manual_note',
      category: 'note',
      content: 'Dra. Mariana pediu para colocar um destaque especial para o tratamento com alinhadores invisíveis.',
      createdAt: '2026-03-16T15:20:00Z',
    },
  ],

  files: [
    {
      id: 'file-1',
      clientId: 'cli-1',
      projectId: 'prj-1',
      name: 'Logo_Barbearia_Vintage_Vetor.svg',
      category: 'logo',
      fileSize: '420 KB',
      fileUrl: 'https://images.unsplash.com/photo-1503951914875-452162b0f3f1?w=400',
      uploadDate: '2026-02-10',
    },
    {
      id: 'file-2',
      clientId: 'cli-1',
      projectId: 'prj-1',
      name: 'Briefing_Respostas_Carlos.pdf',
      category: 'briefing',
      fileSize: '1.2 MB',
      fileUrl: '#',
      uploadDate: '2026-02-10',
    },
    {
      id: 'file-3',
      clientId: 'cli-2',
      projectId: 'prj-2',
      name: 'Manual_Identidade_Visual_OdontoSorriso.pdf',
      category: 'documents',
      fileSize: '4.8 MB',
      fileUrl: '#',
      uploadDate: '2026-03-01',
    },
    {
      id: 'file-4',
      clientId: 'cli-2',
      projectId: 'prj-2',
      name: 'Fotos_Equipe_Alta_Resolucao.zip',
      category: 'images',
      fileSize: '18.4 MB',
      fileUrl: '#',
      uploadDate: '2026-03-05',
    },
  ],

  expenses: [
    {
      id: 'exp-1',
      title: 'Assinatura Figma Professional',
      category: 'tools',
      amount: 75,
      periodicity: 'monthly',
      startDate: '2026-01-01',
      notes: 'Design de interfaces e protótipos',
    },
    {
      id: 'exp-2',
      title: 'Hospedagem VPS Cloud (Hostinger)',
      category: 'hosting',
      amount: 120,
      periodicity: 'monthly',
      startDate: '2026-01-01',
      notes: 'Servidor dos clientes e staging',
    },
    {
      id: 'exp-3',
      title: 'OpenAI API & Anthropic (IA)',
      category: 'ai',
      amount: 80,
      periodicity: 'monthly',
      startDate: '2026-01-01',
      notes: 'Geração de copy e apoio a código',
    },
  ],

  servicePackages: [
    {
      id: 'pkg-1',
      name: 'Landing Page de Alta Conversão',
      description: 'Página única responsiva com copywriting persuasivo, carregamento ultrarrápido e botão flutuante de WhatsApp.',
      suggestedPrice: 1800,
      averageHours: 12,
      includes: [
        'Design exclusivo no Figma',
        'Responsivo para mobile e desktop',
        'Copywriting profissional',
        'Integração com WhatsApp e Pixel',
        'Otimização de velocidade (PageSpeed 90+)',
      ],
    },
    {
      id: 'pkg-2',
      name: 'Site Institucional Multipáginas',
      description: 'Site corporativo de 4 a 6 páginas para empresas que precisam transmitir autoridade e credibilidade.',
      suggestedPrice: 3500,
      averageHours: 24,
      includes: [
        'Páginas: Início, Sobre, Serviços, Depoimentos, Contato',
        'SEO inicial configurado',
        'Painel administrativo para edição',
        'Certificado SSL e hospedagem configurada',
      ],
    },
    {
      id: 'pkg-3',
      name: 'Manutenção & Suporte Mensal',
      description: 'Cuidado contínuo para o site do cliente sempre funcionar rápido, seguro e atualizado.',
      suggestedPrice: 300,
      averageHours: 3,
      includes: [
        'Backups semanais em nuvem',
        'Atualização de plugins e segurança',
        'Até 2 horas de alterações por mês',
        'Monitoramento 24/7 contra quedas',
      ],
    },
  ],
};
